name: eun
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - pip:
      - flask
      - flask-cors
      - requests
      - pandas
      - scikit-learn
      - joblib
      - requests
      - pandas-stubs
