name: hr
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy<2
  - pandas
  - scikit-learn
  - pip
  - pip:
      - flask
      - flask-cors
      - requests
      - pandas-stubs
      - joblib
      - kiwipiepy
      - oracledb

# 콘다 프로필 활성화

#  conda env create -f environment.yml
#  conda activate hr

# pip 으로 numpy, torch, huggingface_hub 버전 맞춰서 설치

#  pip install "numpy<2"
#  pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2
#  pip install \
#  huggingface_hub==0.17.3 \
#  transformers==4.30.2 \
#  sentence-transformers==2.2.2

# 아래 파이썬 파일 만들어서 테스트 해보기 ( libraryTest.py )

#  import numpy
#  import torch
#  from sentence_transformers import SentenceTransformer
#
#  print("numpy:", numpy.__version__)
#  print("torch:", torch.__version__)
#
#  model = SentenceTransformer("all-MiniLM-L6-v2")
#  print("MODEL LOAD OK")