name: hr
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - pip:
      - flask
      - flask-cors
      - requests
#sklearn
#oracledb
#conda install pytorch cpuonly -c pytorch
#pip install sentence-transformers
#pip install --upgrade torch torchvision torchaudio //이건 별도로 한명령어
#pip install --upgrade sentence-transformers transformers //이것도